framework:
    messenger:
        transports:           
            async: 'doctrine://default'
        routing:
            'App\Message\GeneratePayslipMessage': async
            'App\Message\GeneratePayrollReportMessage': async
